version: '3.3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn cosmos.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/backend
      - static:/backend/static
      - media:/backend/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    networks:
      - core
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - core


  nginx:
    container_name: boiler_nginx
    image: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - static:/backend/static
      - media:/backend/media
    ports:
      - 4200:4200
    links:
      - backend
    networks:
      - core
    command: [nginx-debug, '-g', 'daemon off;']

#
#  frontend:
#    container_name: frontend
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    networks:
#      - core
#    command: 'npm run dev'
#    volumes:
#      - ./frontend:/frontend
#      - node-modules:/frontend/node_modules
#    ports:
#      - 3000:3000
#    links:
#      - backend:backend

networks:
  core:

volumes:
  postgres_data:
  static:
  media:
