version: '3.8'

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/cosmos
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    networks:
      - core

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cosmos2
    networks:
      - core

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - core
    command:
      "npm run dev"
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    links:
      - backend:backend


networks:
  core:

volumes:
  postgres_data:
