# Generated by Django 3.2.9 on 2022-06-16 07:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Определяет, следует ли считать эту запись активной. Снимите этот флажок вместо удаления записи.', verbose_name='Активный')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=155, verbose_name='Название баннера')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание баннера')),
                ('link', models.URLField(verbose_name='Ссылка на запись')),
                ('image', models.ImageField(blank=True, upload_to='banners_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'баннер',
                'verbose_name_plural': 'баннеры',
            },
        ),
        migrations.AlterField(
            model_name='resume',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancy', to='main.vacancy', verbose_name='Вакансия'),
        ),
    ]
