# Generated by Django 3.2.9 on 2022-01-20 07:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Определяет, следует ли считать эту запись активной. Снимите этот флажок вместо удаления записи.', verbose_name='Активный')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=155, verbose_name='Название')),
                ('phone', models.CharField(blank=True, default='', max_length=155, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='PartnersTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип партнерства',
                'verbose_name_plural': 'Типы партнерства',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Определяет, следует ли считать эту запись активной. Снимите этот флажок вместо удаления записи.', verbose_name='Активный')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=128, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='products_categories_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория продукции',
                'verbose_name_plural': 'Категории продукции',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='', max_length=64, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, validators=[main.validators.phone_number_validator], verbose_name='Телефон')),
                ('additional', models.TextField(blank=True, default='', verbose_name='Дополнительная информация')),
                ('attachment', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator('pdf', 'doc', 'docx')], verbose_name='Прикрепленный файл')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Определяет, следует ли считать эту запись активной. Снимите этот флажок вместо удаления записи.', verbose_name='Активный')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Название услуги')),
                ('short_description', models.CharField(blank=True, default='', max_length=255, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, default='', verbose_name='Подробное описание')),
                ('image', models.ImageField(blank=True, upload_to='services_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Определяет, следует ли считать эту запись активной. Снимите этот флажок вместо удаления записи.', verbose_name='Активный')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=64, verbose_name='Название')),
                ('responsibility', models.TextField(blank=True, default='', verbose_name='Обязанности')),
                ('requirements', models.TextField(blank=True, default='', verbose_name='Требования')),
                ('advantage', models.TextField(blank=True, default='', verbose_name='Дополнительные преимущества')),
                ('conditions', models.TextField(blank=True, default='', verbose_name='Условия работы')),
                ('key_skills', models.TextField(blank=True, default='', verbose_name='Ключевые навыки')),
                ('employment_type', models.TextField(blank=True, default='', verbose_name='Тип занятости')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Определяет, следует ли считать эту запись активной. Снимите этот флажок вместо удаления записи.', verbose_name='Активный')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=64, verbose_name='Название продукта')),
                ('developer', models.CharField(blank=True, default='', max_length=125, verbose_name='Разработчик продукта')),
                ('version', models.CharField(blank=True, default='', max_length=64, verbose_name='Версия продукта')),
                ('categories', models.ManyToManyField(blank=True, to='main.ProductCategories', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Определяет, следует ли считать эту запись активной. Снимите этот флажок вместо удаления записи.', verbose_name='Активный')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=155, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('link', models.URLField(verbose_name='Ссылка на сайт')),
                ('image', models.ImageField(blank=True, upload_to='partners_images/', verbose_name='Изображение')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.partnerstypes', verbose_name='Тип партнерства')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
    ]
