# Generated by Django 3.2.9 on 2022-01-31 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePages',
            fields=[
                ('pages_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.pages')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'страница услуги',
                'verbose_name_plural': 'страницы услуг',
            },
            bases=('main.pages',),
        ),
    ]
