# Generated by Django 3.2.9 on 2022-02-11 09:43

from django.db import migrations, models
import main.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_servicepages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=155, verbose_name='Название')),
                ('image', models.ImageField(upload_to='images/achievements/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Достижения',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='', max_length=64, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, validators=[main.validators.phone_number_validator], verbose_name='Контактный телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('additional', models.TextField(blank=True, default='', verbose_name='Тема вопроса')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', upload_to='images/news/', verbose_name='Изображение'),
        ),
    ]
