# Generated by Django 3.2.9 on 2022-02-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220211_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='phone',
        ),
        migrations.AddField(
            model_name='contacts',
            name='type',
            field=models.CharField(choices=[('text', 'текст'), ('phone', 'номер телефона'), ('link', 'ссылка'), ('mail', 'почта')], default=None, max_length=300, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='values',
            field=models.CharField(blank=True, default='', max_length=155, verbose_name='Значение'),
        ),
    ]
